name: Linkedin blog post workflow

permissions:
  contents: write

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: {}

jobs:
  linkedin_rss_job:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Post latest blog post to LinkedIn
        uses: Arisamiga/Linkedin-RSS@v1.3.0
        with:
          feed_list: "https://mrmcmuffinz.github.io/posts/index.xml"
          ln_access_token: "${{ secrets.LINKEDIN_ACCESS_TOKEN }}"
          embed_image: "https://mrmcmuffinz.github.io/images/social-card.png"
          last_post_path: ".github/.lastPost.txt"
          commit_user: "linkedin-bot"
          commit_email: "19247363+mrmcmuffinz@users.noreply.github.com"
          commit_message: "Update last LinkedIn post marker"
